### ISSUE TITLE
unable to run hvcc

### ISSUE THREAD

**Issue by magnetophon** [bandithedoge/nur-packages#22]
Thanks for making these packages!

When I try to run hvcc, I get:
```
❯ hvcc
Traceback (most recent call last):
  File "/nix/store/8glm7n36wwj1h6gxj7ck8y422g700bxp-python3.12-hvcc-v0.12.1/bin/.hvcc-wrapped", line 6, in <module>
    from hvcc import main
  File "/nix/store/8glm7n36wwj1h6gxj7ck8y422g700bxp-python3.12-hvcc-v0.12.1/lib/python3.12/site-packages/hvcc/__init__.py", line 31, in <module>
    from hvcc.generators.c2daisy import c2daisy
  File "/nix/store/8glm7n36wwj1h6gxj7ck8y422g700bxp-python3.12-hvcc-v0.12.1/lib/python3.12/site-packages/hvcc/generators/c2daisy/c2daisy.py", line 10, in <module>
    from ..types.meta import Meta, Daisy
  File "/nix/store/8glm7n36wwj1h6gxj7ck8y422g700bxp-python3.12-hvcc-v0.12.1/lib/python3.12/site-packages/hvcc/generators/types/meta.py", line 2, in <module>
    from pydantic import BaseModel, HttpUrl
ModuleNotFoundError: No module named 'pydantic'
```

Any idea what is going on?

**Comment by magnetophon** [comment]
Nevermind, I just noticed that I'm using an outdated version of your repo: <https://github.com/nix-community/nur-combined>

**Comment by magnetophon** [comment]
NOTE: I don't expect you to debug this for me, but it would be really helpful if you could tell me if you've been able to use hvcc on NixOS, and if so, how.

I now installed the version from your repo and ran intpo a weird issue:

I'm trying to compile a simple test patch (osc~ 440 -> dac~) to dpf.
I get:
```
hvcc Patches/test-osc.pd -g dpf -o builds -v
--> Generating C

=== Signal Order ===
__phasor_k~f {frequency:440.0 phase:0.0}
__var_k~f {k:0.5 step:0 reverse:False}
__sub~f
__abs~f
__var_k~f {k:0.25 step:0 reverse:False}
__sub~f
__var_k~f {k:6.283185307179586 step:0 reverse:False}
__mul~f
__mul~f
__mul~f
__mul~f
__var_k~f {k:0.007833333333333 step:0 reverse:False}
__var_k~f {k:-0.166666666666667 step:0 reverse:False}
__fma~f
__fma~f
__add~f
__add~f
AVX: 58.0 cycles / 7.25 cycles per frame
     512 frames @ 1000MHz >= 3.71us
SSE: 55.0 cycles / 13.75 cycles per frame
     512 frames @ 1000MHz >= 7.04us
CPU% #Objs Object Type      Performance
==== ===== ================ ===========
22%  1     __phasor_k~f     Counter({'avx': 13, 'sse': 10})
 4%  5     __var_k~f        Counter({'avx': 2.5, 'sse': 2.5})
10%  2     __sub~f          Counter({'avx': 6, 'sse': 6})
 0%  1     __abs~f          Counter({'avx': 0.5, 'sse': 0.5})
34%  4     __mul~f          Counter({'avx': 20, 'sse': 20})
17%  2     __fma~f          Counter({'avx': 10, 'sse': 10})
10%  2     __add~f          Counter({'avx': 6, 'sse': 6})
--> Generating DPF plugin
  1) Error c2dpf: [Errno 13] Permission denied: '/home/bart/Documents/plugdata/builds/plugin/source'
Total compile time: 190.37ms
```

So I tried:
``` 
chmod -R 777 builds/
ls -al builds/plugin/
total 23
drwxrwxrwx 2 bart users    3 Jan  1  1970 .
drwxrwxrwx 6 bart users    7 Nov 13 14:26 ..
-rwxrwxrwx 1 bart users 1071 Jan  1  1970 README.md
```
but on the next run of hvcc, I get the same error.

**Comment by bandithedoge** [comment]
Try the `-o <path>` argument.

I had a similar issue when trying to compile https://github.com/MikeMorenoDSP/LIRA-8 some time ago but gave up thinking it's either user error (I barely have any experience with PD) or the usual Nix store path shenanigans. Tried again just now and specifying the output directory seems to work fine.

**Comment by bandithedoge** [comment]
Scratch that, I noticed just now that you actually did use the `-o` argument. I only checked compiling to C before and tried DPF now. I tried running hvcc straight from the cloned repo through Poetry without Nix and it seems to work just fine. So it *is* a packaging issue after all.

**Comment by magnetophon** [comment]
Thanks!
I couldn't tell from your reply: have you tried compiling a dpf using your package?

**Comment by magnetophon** [comment]
In the meantime I've installed an ubuntu distrobox, and was able to compile a working binary using that.
Not ideal, but at least it works!

**Comment by dromer** [comment]
> I had a similar issue when trying to compile https://github.com/MikeMorenoDSP/LIRA-8 some time ago 

LIRA-8 is incompatible with the Heavy Compiler, so that likely failed for a very different reason.

**Comment by bandithedoge** [comment]
> Thanks! I couldn't tell from your reply: have you tried compiling a dpf using your package?

Do you mean compiling a DPF plugin generated from hvcc? In that case no, since I'm running into the same permissions issue. Compiling to C works fine, though.



> > I had a similar issue when trying to compile https://github.com/MikeMorenoDSP/LIRA-8 some time ago
> 
> LIRA-8 is incompatible with the Heavy Compiler, so that likely failed for a very different reason.

Thanks for the heads up. I hadn't reached that "different reason" though, since I was unable to compile a DPF plugin from hvcc in the first place.

**Comment by magnetophon** [comment]
OK, good to know it's not just my system.

Now how could we try to figure out the root cause?

**Comment by bandithedoge** [comment]
At first I thought it may be related to a DPF git submodule but hvcc does not create git repositories and requires you to supply DPF yourself. I'm not at all familiar with the inner workings of hvcc, so @dromer is our best bet for now.

**Comment by magnetophon** [comment]
> @dromer is our best bet for now.

Well, they (rightfully) point out that this seems to be a NixOS issue, and they are not familiar with it's inner workings...

¯\\\_(ツ)_/¯

**Comment by dromer** [comment]
@bandithedoge it's definitely something that has only been reported on NixOS.

What is odd that it only happens after the other code generation steps are already done.
This is where I think it's going wrong: https://github.com/Wasted-Audio/hvcc/blob/develop/hvcc/generators/c2dpf/c2dpf.py#L68
